### ISSUE TITLE
removing xyz coords from the tooltip?

### ISSUE THREAD

**Issue by monicathieu** [ggseg/ggseg3d#10]
Hi there,

First off, this package is incredible! I have been struggling for SO long to find a nice way to render stats calculated from Freesurfer-parcellated brains onto an inflated brain with the correct ROI demarcations. I'm excited to use it in my next presentation 😄 

I would like to remove the xyz coordinates from the tooltip that appears upon hovering on any of the ROIs in the default `ggseg3d()` plot. I'm still a bit new to Plotly, so pardon me if I have simply missed the correct argument for this, but I don't know if there is a way to remove elements from a plot tooltip after the plot has already been generated. It seems like the only way is to modify the `hoverinfo` argument inside of `add_trace()` when the mesh is first put on the plot.

If this is the case, would it be possible to add an argument such as `ggseg3d(options.tooltip = "text")` that passes down into `add_trace(hoverinfo = options.tooltip)` to allow modifying the tooltip?

It might be less of a headache to implement it with `...`, actually, such that `ggseg(...)` would be able to pass any extra arguments down into the primary `add_trace()` call that draws the mesh on the Plotly plot. That way you wouldn't have to hard-code any extra arguments!

Let me know what you think, and/or if I've missed something super obvious!

---
PS: For what it's worth, I also dug around a bit trying things like the following to at least round the number of digits showing up in the tooltip as a workaround:

```r
ggseg3d() %>%
  layout(xaxis = list(hoverformat = ".3f")
```

but nothing seems to change! I looked in the Plotly docs and I'm not sure if `mesh3d` traces have an `xaxis` or `yaxis` layout element that can be modified by piping the Plotly object through `layout()`. Rats!

**Comment by drmowinckels** [comment]
Hi :)

Great suggestion, and so easy to implement. I have added an ellipsis that would feed additional arguments to add_trace.

The only version I got working for me was

```r
ggseg3d(hovertemplate = " ")  # string with a single white space
```

![image](https://user-images.githubusercontent.com/14014329/93850991-935c5680-fcaf-11ea-8f07-0a57d338bee6.png)

My experience when developing this is that the mesh-plots are different than other plots in plotly, and more uncommon to use, so finding the correct syntax for the adaptations one wants is quite hard!

**Comment by monicathieu** [comment]
You are a hero for patching this so quickly! And I think the `hoverinfo` tag may be a little less finicky than `hovertemplate` here, perhaps for the reasons you described about Plotly mesh plots being different--

```r
library(ggseg3d)
ggseg3d(hoverinfo = "name")
```

![image](https://user-images.githubusercontent.com/9875687/93899497-feab2600-fcb9-11ea-8504-16211f4ad16b.png)

Woohoo! Thank you 🎉

**Comment by drmowinckels** [comment]
great! It was a _very_ easy thing to add, and you gave me a clear idea of what you needed and wanted. 

:)
