### ISSUE TITLE
Problem with Installing the Vignettes

### ISSUE THREAD

**Issue by yusaiwen** [ggseg/ggseg3d#12]
The ggseg3d was successfully installed with output showed below:

> devtools::install_github("LCBC-UiO/ggseg3d", build_vignettes = TRUE, force=TRUE)
Downloading GitHub repo LCBC-UiO/ggseg3d@HEAD
✓  checking for file ‘/private/var/folders/4w/mthnd8nj7pxcrqbdc9q4wyd40000gn/T/RtmpsrDUdn/remotes272376ab5fa6/LCBC-UiO-ggseg3d-dfb71e8/DESCRIPTION’ ...
─  preparing ‘ggseg3d’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘ggseg3d/man/figures’
─  building ‘ggseg3d_1.6.01.tar.gz’
   
* installing *source* package ‘ggseg3d’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ggseg3d)

load the library ggsed3d met with no trouble:
> library(ggseg3d)

However vignette is not working:
> vignette("ggseg3d")
Warning message:
vignette ‘ggseg3d’ not found 

Actually, ggseg event cannot succeed in installing the Vignettes. Here is some output:

> remotes::install_github("LCBC-UiO/ggseg", build_vignettes = TRUE)
Downloading GitHub repo LCBC-UiO/ggseg@HEAD
✓  checking for file ‘/private/var/folders/4w/mthnd8nj7pxcrqbdc9q4wyd40000gn/T/RtmpsrDUdn/remotes2723558afdd2/LCBC-UiO-ggseg-9330d87/DESCRIPTION’ ...
─  preparing ‘ggseg’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (17.9s)
   --- re-building ‘externalData.Rmd’ using rmarkdown
   --- finished re-building ‘externalData.Rmd’
   
   --- re-building ‘freesurfer_files.Rmd’ using rmarkdown
   Quitting from lines 11-20 (freesurfer_files.Rmd) 
   Error: processing vignette 'freesurfer_files.Rmd' failed with diagnostics:
   there is no package called 'here'
   --- failed re-building ‘freesurfer_files.Rmd’
   
   --- re-building ‘ggseg.Rmd’ using rmarkdown
   --- finished re-building ‘ggseg.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘freesurfer_files.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'ggseg' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> --- failed re-building ‘freesurfer_files.Rmd’
E> 
E> --- re-building ‘ggseg.Rmd’ using rmarkdown
E> --- finished re-building ‘ggseg.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘freesurfer_files.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted

> ggseg()
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggseg_1.5.5   ggplot2_3.3.2

loaded via a namespace (and not attached):
 [1] compiler_4.0.2    pillar_1.4.6      prettyunits_1.1.1 remotes_2.2.0    
 [5] tools_4.0.2       testthat_3.0.0    digest_0.6.27     pkgbuild_1.1.0   
 [9] pkgload_1.1.0     memoise_1.1.0     lifecycle_0.2.0   tibble_3.0.4     
[13] gtable_0.3.0      pkgconfig_2.0.3   rlang_0.4.8       cli_2.1.0        
[17] rstudioapi_0.13   curl_4.3          dplyr_1.0.2       withr_2.3.0      
[21] generics_0.1.0    vctrs_0.3.5       desc_1.2.0        fs_1.5.0         
[25] devtools_2.3.2    tidyselect_1.1.0  rprojroot_2.0.2   grid_4.0.2       
[29] glue_1.4.2        R6_2.5.0          processx_3.4.4    fansi_0.4.1      
[33] sessioninfo_1.1.1 farver_2.0.3      tidyr_1.1.2       purrr_0.3.4      
[37] callr_3.5.1       magrittr_2.0.1    scales_1.1.1      ps_1.4.0         
[41] ellipsis_0.3.1    usethis_1.6.3     assertthat_0.2.1  colorspace_2.0-0 
[45] munsell_0.5.0     crayon_1.3.4     
> dk
# A tibble: 90 x 6
   atlas hemi  region              side    label               ggseg          
   <chr> <chr> <chr>               <chr>   <chr>               <list>         
 1 dk    left  NA                  lateral NA                  <tibble [24 × …
 2 dk    left  bankssts            lateral lh_bankssts         <tibble [79 × …
 3 dk    left  caudal middle fron… lateral lh_caudalmiddlefro… <tibble [102 ×…
 4 dk    left  fusiform            lateral lh_fusiform         <tibble [60 × …
 5 dk    left  inferior parietal   lateral lh_inferiorparietal <tibble [116 ×…
 6 dk    left  inferior temporal   lateral lh_inferiortemporal <tibble [182 ×…
 7 dk    left  lateral occipital   lateral lh_lateraloccipital <tibble [85 × …
 8 dk    left  lateral orbitofron… lateral lh_lateralorbitofr… <tibble [70 × …
 9 dk    left  middle temporal     lateral lh_middletemporal   <tibble [188 ×…
10 dk    left  pars opercularis    lateral lh_parsopercularis  <tibble [82 × …
# … with 80 more rows

**Comment by drmowinckels** [comment]
Hi.

We have on purpose removed the ggseg3d vignettes from the pacakge. They are too large, and since they are plotly interactive widges, they cannot be embeded into the installed R vignettes. They are therefore only available at the package online documentation: https://lcbc-uio.github.io/ggseg3d/

As for the ggseg vignettes, there has been an error making these not build correctly in certain environments. We are still trying to understand why and which environments are affected, and how to fix it. This is a know and reported issue: https://github.com/LCBC-UiO/ggseg/issues/36

However, you can also see the online documentation: https://lcbc-uio.github.io/ggseg/
