### ISSUE TITLE
request to add ?h.pial to ggseg3d

### ISSUE THREAD

**Issue by octlie** [ggseg/ggseg3d#13]
Dear All, 

Can this be done (timely)? I would really appreciate it. While working on ?h.pial is not ideal for mapping/atlasing, it is important to have anatomical correspondence for the more flattened surfaces (inflated, LCBC and others), especially since we plan creating some educational maps re sampling certain scouts etc. So one way to use the ?h.pial along with a flattened correspondent in the same figure, for comparison. Please let me know, many thanks, Octavian

**Comment by drmowinckels** [comment]
We will not add pial surfaces to the existing atlases, as the data files are already large and pial surfaces hide too. much information to be of general use.

However, you can create pial surfaces for ggseg3d using the pipeline in ggsegExtra for creating new surface atlases. 
Make sure to specify you want to create a pial surface to the creation command. 

https://lcbc-uio.github.io/ggsegExtra/articles/createdkt.html#the-3d-atlas

**Comment by octlie** [comment]
Dear Athanasia, 

Thank you for your guidance. I am new to this. I assume that to make the pial surf, this is the piece of code you are referring to 
# Make  3d ----
dkt_3d <- make_aparc_2_3datlas(annot = "aparc.DKTatlas",
                               output_dir = "~/Desktop/")

How do I add the 'pial' option? Thank you again, Octavian

**Comment by drmowinckels** [comment]
If you look at the function documentation, you will see the function takes a `surface` argument. 
This can contain any Freesurfer surface available for a given subject.

https://lcbc-uio.github.io/ggsegExtra/reference/make_aparc_2_3datlas.html

You can therefore do

```r
dkt_3d <- make_aparc_2_3datlas(annot = "aparc.DKTatlas",
                               surface = "pial",
                               output_dir = "~/Desktop/")
```

**Comment by octlie** [comment]
Got it, thank you again!
I installed ggseg +checked successfully (- the vignettes), plots are beautiful. 
I also installed ggseg3d without errors (also without vignettes, which have been removed, it sounds).
In contrast to ggseg well check, I get an error with ggseg3d:

> library(ggseg3d)
> p <- ggseg3d(atlas=dk_3d) %>% 
+   remove_axes() %>% 
+   pan_camera("right lateral")
Error in ggseg3d(atlas = dk_3d) %>% remove_axes() %>% pan_camera("right lateral") : 
  could not find function "%>%"

I repeated the install, same error. I have R 3.6.3 on Ubuntu 16.04. Please advise, is this a know issue?, thank you very much, Octavian

**Comment by octlie** [comment]
OK. The "%>%" was due to some libraries missing (which I would have to load every time I run ggseg3d. The code below does not trigger any error, but nothing happens, no plot is created (I reran ggseg fresh install with sudo R  and remotes several times):

library(magrittr) 
library(dplyr)
library(ggseg3d)
p <- ggseg3d(atlas=dk_3d) %>% 
  remove_axes() %>% 
  pan_camera("right lateral")

Please advise, thank you again, Octavian

**Comment by drmowinckels** [comment]
you are saving the plot to a variable you call `p`. to prduce the plot you must either call `p` after creating it, or remove `p <-` frm the code.
