### ISSUE TITLE
ROI borders

### ISSUE THREAD

**Issue by Keikokunitoki** [ggseg/ggseg3d#16]
Thank you for developing this fantastic package.
Is there any way to add ROI borders like with ggseg?

**Comment by danieltomasz** [comment]
hi @Keikokunitoki , to that I converted 3d atlas to 2d with ggsegExtra package

**Comment by drmowinckels** [comment]
Hi @Keikokunitoki !

Like @danieltomasz points out, to do that you'll need to convert it to ggseg. Because of how ggseg3d works, adding borders is actually quite difficult, so we have not spent time trying to figure it out.
