### ISSUE TITLE
Can ggseg3d plot specific regions from the DK atlas?

### ISSUE THREAD

**Issue by bertram0611** [ggseg/ggseg3d#20]
Hi experts,

I want to plot a specific region, such as the temporal pole from the DK atlas.
Put another way, I want to keep the color of the temporal pole, simultaneously changing other regions to white.
How can I realize this purpose?

Best,
Lin

**Comment by bertram0611** [comment]
Hi

I am also wondering how to use the script to save 3d figures as 2d files(PDF, tiff, etc.) with a high resolution for publication.

Best,
Lin

**Comment by zhangjb35** [comment]
For your second question, try this code. assume p is you object generated by ggseg3d, you should install reticulate and config it successfully:
```r
library(reticulate)
use_miniconda('r-reticulate')
py_run_string("import sys")
save_image(p, "left.png",scale=3)
gc()
```

**Comment by bertram0611** [comment]
Hi,

I tried your scripts in R. But I got the following error messages. Do you know how to fix it?

#####################################
Error in save_image(p, "left.png", scale = 3) : 
  could not find function "save_image"

**Comment by zhangjb35** [comment]
> Hi,
> 
> I tried your scripts in R. But I got the following error messages. Do you know how to fix it?
> 
> ##################################### Error in save_image(p, "left.png", scale = 3) : could not find function "save_image"

you should install reticulate first. https://rdrr.io/cran/plotly/man/save_image.html

**Comment by bertram0611** [comment]
> > Hi,
> > I tried your scripts in R. But I got the following error messages. Do you know how to fix it?
> > ##################################### Error in save_image(p, "left.png", scale = 3) : could not find function "save_image"
> 
> you should install reticulate first. https://rdrr.io/cran/plotly/man/save_image.html

Thank you very much! The issue has be solved.

Best,
Lin
