### ISSUE TITLE
colorbar title instead of "z"

### ISSUE THREAD

**Issue by ccjake** [ggseg/ggseg3d#4]
I would like to change the title of the right side colorbar, but layout method in plotly failed.

**Comment by drmowinckels** [comment]
could you please provide the code that is not working so we can look into it?

**Comment by ccjake** [comment]
Hallo, 

Thanks for reply.
I took a closer look at the source code. You are using add_trace to create the colorbar instead of  using the coloraxis or something come with plotly, so I think that's the reason, why the layout did not work. I have changed a little code in the source code and now it works.


```
p <- ggseg3d(.data = example1Data,
             atlas = desterieux_neu,
             colour = "wert", text = "beschreibung",
             surface = "LCBC",
             palette = c("red" = 1, "yellow" = 2, "blue" = 3),
             hemisphere = c("left","right"),
             show.legend = FALSE) 

 
 %>% layout(coloraxis=list(colorbar=list(title=list(text="not work"))))

```
The above code cannot change the title.


```
p <- ggseg3d(.data = example1Data,  
             atlas = desterieux_neu,
             colour = "wert", text = "beschreibung",
             surface = "LCBC",
             palette = c("red" = 1, "yellow" = 2, "blue" = 3),
             hemisphere = c("left","right"),
             show.legend = FALSE)
f <- get_farbe(c("red" = 1, "yellow" = 2, "blue" = 3))
dt_leg <- dplyr::mutate(f, x = 0, y = 0, z = 0)
p = plotly::add_trace(p, data = dt_leg, x = ~x, y = ~y,
                      z = ~z, intensity = ~values,
                      colorscale = unname(dt_leg[,c("norm", "hex")]),
                      colorbar=list(title=list(text="mm")), type = "mesh3d")

```
The second piece of code can chang the title rightly, they are basically the code in "ggseg3d()" . Maybe it's not the best way, but it works on me.

Best wishes.

**Comment by drmowinckels** [comment]
Hey!

Thanks for digging into the code and finding the culprit, and also providing a solution. 

I have now added an argument where you can control the `colourbar` in the add_trace for the colourbar. It's in commit [5fc8fbf52aa](https://github.com/LCBC-UiO/ggseg3d/commit/5fc8fbf52aa2de4d62d12c7f4e0adb47a3943722). 

Check that out and see if that behaves more like you expect :)

**Comment by ccjake** [comment]
Hallo,

Yes, it works perfectly. Thanks for update!
