### ISSUE TITLE
glasser_3d atlas 

### ISSUE THREAD

**Issue by AthinaRA** [ggseg/ggseg3d#7]
Hi 

I am just getting acquainted with ggseg3d. However I am having issue getting it to work with the glasser_3d atlas. 

Running the below I am not seeing parcellated 3d regions - only a glass brain. I have loaded the ggsegGlasser atlas ie could view the glasser_3d tibble. Any idea what the issue could be ? Pls and thank you - Athina.

ggseg3d(atlas = glasser_3d,
             surface = "LCBC",
             hemisphere = c("left","right")) %>% 
  add_glassbrain()

**Comment by drmowinckels** [comment]
The glasser atlas is a cortical atlas, and should not be paired with a glass brain. 

You should see the atlas just fine if you remove it, as it is overplotting the actual atlas.


```
library(ggseg3d)
library(ggsegGlasser)

ggseg3d(atlas = glasser_3d,
        surface = "LCBC",
        hemisphere = c("left","right"))
```

![image](https://user-images.githubusercontent.com/14014329/87401666-b802c680-c5ba-11ea-9fa5-5f3c0b87dce1.png)

**Comment by AthinaRA** [comment]
Thank you - worked perfectly !
